### PR TITLE
Make search on member name case-insensitive

### PR DESCRIPTION
**Pull request by raypereda**
Searches are failing because they are case-sensitive.
This is a temporary fix.

### CODE REVIEW

**Comment by raypereda** [comment]
@socalpilot Is this they way you recommend doing case-insensitive search?

**Comment by socalpilot** [comment]
Looks good to me.

**Comment by raypereda** [comment]
@socalpilot I just merged you pull request.

**Comment by socalpilot** [comment]
What's next?

**Comment by raypereda** [comment]
We do our first pull request on GitHub enterprise. 

-Ray

**Pull request merged**
